### PR TITLE
Add a gitignore

### PR DESCRIPTION
**Pull request by pradyunsg**

### CODE REVIEW

**Comment by pradyunsg** [comment]
Seems like there's no interest in putting resources into maintaining this project.

**Comment by theonewolf** [comment]
Hey @pradyunsg sorry this took so long to circle around on!

If you could resubmit your PRs (although I see the repo is deleted) I will merge them.

Alternatively, I'll treat your PRs as issues and can fix them for you.

**Comment by pradyunsg** [comment]
> Alternatively, I'll treat your PRs as issues and can fix them for you.

Please feel free to reuse the changes from my PRs. I don't think I'll be re-submitting them FWIW.

I'm mostly just trimming my open PRs, to minimize things I'm responsible for. Sorry if me closing this and deleting my repo came across as rude. :)

**Comment by theonewolf** [comment]
> Sorry if me closing this and deleting my repo came across as rude.

@pradyunsg I'd say warn before deleting in the future as a better practice.  Or just close, but wait sometime before deleting.

That said, it did serve as a wake up call to the project, so you accomplished something!

**Pull request closed without merging**
